# Generated by Django 2.2.24 on 2021-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='description',
            new_name='descriptiontest',
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
