# Generated by Django 2.2.24 on 2021-06-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210628_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='title',
            new_name='titleTest',
        ),
    ]
